# Generated by Django 6.0.5 on 2026-05-11 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_distributor_created_at_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='users.distributor')),
            ],
        ),
    ]
