# Generated by Django 6.0.5 on 2026-05-11 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('reports', '0001_initial'),
        ('users', '0002_remove_distributor_created_at_alter_user_is_active'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereport',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='report',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.distributor'),
        ),
        migrations.AddField(
            model_name='purchasereport',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_report', to='reports.report'),
        ),
        migrations.AddField(
            model_name='profitlossreport',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profit_loss_report', to='reports.report'),
        ),
        migrations.AddField(
            model_name='salereport',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='salereport',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_report', to='reports.report'),
        ),
    ]
