# Generated by Django 6.0.5 on 2026-05-11 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('users', '0002_remove_distributor_created_at_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_input', models.TextField()),
                ('converted_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_orders', to='users.distributor')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_order', to='orders.order')),
            ],
        ),
    ]
